# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -g -I/Users/Charlie/Dropbox/CS50/Labs/proj/samples/nanoProj/include   

CXX_DEFINES = 

